### ISSUE TITLE
CKAN integration

### ISSUE THREAD

**Issue by mheguy** [tomforwood/kerbal-impact#7]
Hi,

Just wanted to give you a heads up that the latest version of impact failed to be indexed into CKAN because we're currently unable to install mods when the mod's contents don't reside in a folder.

If you're still interested in being indexed in CKAN the easiest solution (in my opinion) is to just upload a new .zip to the same github release. Preferably with a folder name identical to previous releases (ie. `Impact`).

All the best.

**Comment by tomforwood** [comment]
Thanks, I have updated the zip

**Comment by mheguy** [comment]
I appreciate it!
