### ISSUE TITLE
Seismometer model texture filename creates ERR in log file

### ISSUE THREAD

**Issue by wile1411** [tomforwood/kerbal-impact#9]
The texture file currently being use by the Seismometer part current works...

However the syntax for the "texture" property only expects a space after the path when you are replacing a one texture with another. It's probably best to future proof this by removing the space from the config file reference as well as within the module file.

Currently: seismometer.cfg
texture = Impact/Parts/Seismometer/texture or

generates: KSP.log
[LOG 23:55:45.273] PartLoader: Compiling Part 'Impact/Parts/Seismometer/seismometer/Impact Seismometer'
[ERR 23:55:45.275] PartCompiler: Cannot replace texture as texture replacement string is invalid. Syntax is 'origTextureName newTextureURL'

Recommend: seismometer.cfg
texture = Impact/Parts/Seismometer/textureor

textureor.png (change file name)

seismometer.mu (Update texture reference to textureor.png within model)

**Comment by tomforwood** [comment]
Thanks, I'll fix it in the next release
